// resources/js/Layouts/Partials/AppTopbar.jsx
import React, { useRef, useState } from 'react';
import { Link, router } from '@inertiajs/react';
import { Button } from 'primereact/button';
import { Menu } from 'primereact/menu';
import { Badge } from 'primereact/badge';
import { Avatar } from 'primereact/avatar';
import { useLayout } from './LayoutContext';
import ApplicationLogo from '@/Components/ApplicationLogo';

const AppTopbar = () => {
    const { toggleMenu } = useLayout();
    const menu = useRef(null);

    const items = [
        {
            label: 'Profile',
            items: [
                {
                    label: 'Settings',
                    icon: 'pi pi-cog',
                    command: () => {
                        // Add settings navigation
                    }
                },
                {
                    label: 'Messages',
                    icon: 'pi pi-inbox',
                    badge: 2
                },
                {
                    label: 'Logout',
                    icon: 'pi pi-sign-out',
                    command: () => {
                        router.post(route('logout'), {}, {
                            onSuccess: () => {
                                window.location = '/';
                            }
                        });
                    }
                }
            ]
        }
    ];

    const toggle = (event) => {
        menu.current.toggle(event);
    };

    const itemTemplate = (item) => {
        return (
            <a className="flex items-center p-menuitem-link">
                <span className={item.icon} />
                <span className="ml-2">{item.label}</span>
                {item.badge && <Badge value={item.badge} className="ml-auto" />}
                {item.shortcut && (
                    <span className="ml-auto border border-surface rounded bg-emphasis text-muted-color text-xs p-1">
                        {item.shortcut}
                    </span>
                )}
            </a>
        );
    };

    return (
        <div className="layout-topbar">
            <div className="layout-topbar-logo-container">
                <button className="layout-menu-button layout-topbar-action" onClick={toggleMenu}>
                    <i className="pi pi-bars"></i>
                </button>
                <Link href="/" className="layout-topbar-logo">
                    <span>
                        <ApplicationLogo />
                    </span>
                </Link>
            </div>

            <div className="layout-topbar-actions">
                <div className="layout-topbar-menu hidden lg:block">
                    <div className="layout-topbar-menu-content">
                        <button type="button" className="layout-topbar-action">
                            <i className="pi pi-inbox"></i>
                            <span>Messages</span>
                        </button>
                        <Button
                            type="button"
                            label="Profile"
                            icon="pi pi-user"
                            className="layout-topbar-action1"
                            outlined
                            onClick={toggle}
                            aria-haspopup
                            aria-controls="overlay_menu"
                        />
                        <Menu
                            model={items}
                            className="w-full md:w-60"
                            id="overlay_menu"
                            popup
                            ref={menu}
                        >
                            <div className="p-menu-end">
                                <button className="relative overflow-hidden w-full border-0 bg-transparent flex items-start p-2 pl-4 hover:bg-surface-100 dark:hover:bg-surface-800 rounded-none cursor-pointer transition-colors duration-200">
                                    <Avatar
                                        image="https://primefaces.org/cdn/primevue/images/avatar/amyelsner.png"
                                        className="mr-2"
                                        shape="circle"
                                    />
                                    <span className="inline-flex flex-col items-start">
                                        <span className="font-bold">Amy Elsner</span>
                                        <span className="text-sm">Admin</span>
                                    </span>
                                </button>
                            </div>
                        </Menu>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default AppTopbar;

// resources/js/Layouts/Partials/AppTopbar.vue
<script setup>
import ApplicationLogo from "@/Components/ApplicationLogo.vue";
import { Link, router } from "@inertiajs/vue3";
import { computed } from "vue";
import { useLayout } from "./LayoutComposable";

const { toggleMenu } = useLayout();

// detect active route
const current = computed(() => route().current());

// highlight helper
const isActive = (name) => current.value.startsWith(name);
</script>

<template>
    <div
        class="layout-topbar flex items-center justify-between px-4 bg-white border-b shadow-sm"
    >
        <!-- LEFT SIDE: Menu Toggle + Logo -->
        <div class="flex items-center gap-3">
            <button
                class="layout-menu-button layout-topbar-action"
                @click="toggleMenu"
            >
                <i class="pi pi-bars text-xl"></i>
            </button>

            <Link href="/" class="layout-topbar-logo flex items-center gap-2">
                <ApplicationLogo class="h-8 w-auto" />
            </Link>
        </div>

        <!-- RIGHT SIDE: ACTIONS -->
        <div class="flex items-center gap-4">
            <!-- POS BUTTON (TOPBAR BUTTON — NOT DROPDOWN) -->
            <button
                @click="router.visit(route('pos.index'))"
                class="flex items-center gap-2 px-3 py-2 rounded-lg transition"
                :class="
                    isActive('pos.index')
                        ? 'bg-indigo-600 text-white shadow-sm'
                        : 'hover:bg-indigo-50 text-slate-700'
                "
            >
                <i class="pi pi-desktop text-lg"></i>
                <span class="text-sm font-medium">POS</span>
            </button>

            <!-- ORDERS BUTTON -->
            <button
                @click="router.visit(route('pos.orders.index'))"
                class="flex items-center gap-2 px-3 py-2 rounded-lg transition"
                :class="
                    isActive('pos.orders.index')
                        ? 'bg-emerald-600 text-white shadow-sm'
                        : 'hover:bg-emerald-50 text-slate-700'
                "
            >
                <i class="pi pi-receipt text-lg"></i>
                <span class="text-sm font-medium">Orders</span>
            </button>

            <!-- MESSAGES BUTTON -->
            <button
                type="button"
                class="layout-topbar-action flex items-center gap-2 hover:text-primary"
            >
                <i class="pi pi-inbox text-lg"></i>
                <span class="hidden md:block text-sm">Messages</span>
            </button>

            <!-- PROFILE DROPDOWN -->
            <Menu
                ref="menu"
                :popup="true"
                id="top_profile_menu"
                :model="[
                    {
                        label: 'Settings',
                        icon: 'pi pi-cog',
                        command: () => router.visit(route('profile.edit')),
                    },
                    {
                        label: 'Logout',
                        icon: 'pi pi-sign-out',
                        command: () => router.post(route('logout')),
                    },
                ]"
            />

            <Button
                type="button"
                label="Profile"
                icon="pi pi-user"
                class="layout-topbar-action1"
                variant="outlined"
                @click="$refs.menu.toggle($event)"
            />
        </div>
    </div>
</template>
