// resources/js/Layouts/AuthenticatedLayout.vue
<script setup>
import { useLayout } from '@/Layouts/Partials/LayoutComposable';
import { computed, ref, watch } from 'vue';
import AppFooter from '@/Layouts/Partials/AppFooter.vue';
import AppSidebar from '@/Layouts/Partials/AppSidebar.vue';
import AppTopbar from '@/Layouts/Partials/AppTopbar.vue';
import FavIcons from '@/Layouts/Partials/FavIcons.vue';

const { layoutConfig, layoutState, isSidebarActive } = useLayout();

const outsideClickListener = ref(null);

watch(isSidebarActive, (newVal) => {
    if (newVal) {
        bindOutsideClickListener();
    } else {
        unbindOutsideClickListener();
    }
});

const containerClass = computed(() => {
    return {
        'layout-overlay': layoutConfig.menuMode === 'overlay',
        'layout-static': layoutConfig.menuMode === 'static',
        'layout-static-inactive': layoutState.staticMenuDesktopInactive && layoutConfig.menuMode === 'static',
        'layout-overlay-active': layoutState.overlayMenuActive,
        'layout-mobile-active': layoutState.staticMenuMobileActive
    };
});

function bindOutsideClickListener() {
    if (!outsideClickListener.value) {
        outsideClickListener.value = (event) => {
            if (isOutsideClicked(event)) {
                layoutState.overlayMenuActive = false;
                layoutState.staticMenuMobileActive = false;
                layoutState.menuHoverActive = false;
            }
        };
        document.addEventListener('click', outsideClickListener.value);
    }
}

function unbindOutsideClickListener() {
    if (outsideClickListener.value) {
        document.removeEventListener('click', outsideClickListener);
        outsideClickListener.value = null;
    }
}

function isOutsideClicked(event) {
    const sidebarEl = document.querySelector('.layout-sidebar');
    const topbarEl = document.querySelector('.layout-menu-button');

    return !(sidebarEl.isSameNode(event.target) || sidebarEl.contains(event.target) || topbarEl.isSameNode(event.target) || topbarEl.contains(event.target));
}
</script>

<template>
    <FavIcons />
    <div class="layout-wrapper bg-blue-50" :class="containerClass">
        <app-topbar></app-topbar>
        <app-sidebar></app-sidebar>
        <div class="layout-main-container">
            <div class="layout-main">
                <slot></slot>
            </div>
            <app-footer></app-footer>
        </div>
        <div class="layout-mask animate-fadein"></div>
    </div>
    <Toast />
</template>

// resources/js/Layouts/AuthenticatedLayout.jsx
import React, { useState, useEffect, useRef } from 'react';
import { Toast } from 'primereact/toast';
import { LayoutProvider, useLayout } from '@/Layouts/Partials/LayoutContext';
import AppFooter from '@/Layouts/Partials/AppFooter';
import AppSidebar from '@/Layouts/Partials/AppSidebar';
import AppTopbar from '@/Layouts/Partials/AppTopbar';
import FavIcons from '@/Layouts/Partials/FavIcons';

const AuthenticatedLayoutContent = ({ children }) => {
    const { layoutConfig, layoutState, isSidebarActive } = useLayout();
    const outsideClickListener = useRef(null);

    useEffect(() => {
        if (isSidebarActive) {
            bindOutsideClickListener();
        } else {
            unbindOutsideClickListener();
        }

        return () => {
            unbindOutsideClickListener();
        };
    }, [isSidebarActive]);

    const bindOutsideClickListener = () => {
        if (!outsideClickListener.current) {
            outsideClickListener.current = (event) => {
                if (isOutsideClicked(event)) {
                    const { setLayoutState } = useLayout();
                    setLayoutState(prev => ({
                        ...prev,
                        overlayMenuActive: false,
                        staticMenuMobileActive: false,
                        menuHoverActive: false
                    }));
                }
            };
            document.addEventListener('click', outsideClickListener.current);
        }
    };

    const unbindOutsideClickListener = () => {
        if (outsideClickListener.current) {
            document.removeEventListener('click', outsideClickListener.current);
            outsideClickListener.current = null;
        }
    };

    const isOutsideClicked = (event) => {
        const sidebarEl = document.querySelector('.layout-sidebar');
        const topbarEl = document.querySelector('.layout-menu-button');

        return !(
            sidebarEl?.isSameNode(event.target) ||
            sidebarEl?.contains(event.target) ||
            topbarEl?.isSameNode(event.target) ||
            topbarEl?.contains(event.target)
        );
    };

    const containerClass = `layout-wrapper ${layoutConfig.menuMode === 'overlay' ? 'layout-overlay' : ''
        } ${layoutConfig.menuMode === 'static' ? 'layout-static' : ''} ${layoutState.staticMenuDesktopInactive && layoutConfig.menuMode === 'static'
            ? 'layout-static-inactive'
            : ''
        } ${layoutState.overlayMenuActive ? 'layout-overlay-active' : ''} ${layoutState.staticMenuMobileActive ? 'layout-mobile-active' : ''
        }`;

    return (
        <>
            <FavIcons />
            <div className={containerClass}>
                <AppTopbar />
                <AppSidebar />
                <div className="layout-main-container">
                    <div className="layout-main">
                        {children}
                    </div>
                    <AppFooter />
                </div>
                <div className="layout-mask animate-fadein"></div>
            </div>
            <Toast />
        </>
    );
};

const AuthenticatedLayout = ({ children }) => {
    return (
        <LayoutProvider>
            <AuthenticatedLayoutContent>
                {children}
            </AuthenticatedLayoutContent>
        </LayoutProvider>
    );
};

export default AuthenticatedLayout;
